### ISSUE TITLE
NPE on setReleaseVersionsTycho step

### ISSUE THREAD

**Issue by pfink** [shillner/unleash-maven-plugin#115]
Under certain circumstances, during setReleaseVersionsTycho step, a NullPointerException is thrown:

```
[ERROR] An exception was caught while processing the workflow step with id 'setReleaseVersionsTycho'.
java.lang.NullPointerException
        at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.lambda$adaptProjectMetadataWithNewVersions$0(AbstractTychoVersionsStep.java:98)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.adaptProjectMetadataWithNewVersions(AbstractTychoVersionsStep.java:93)
        at com.itemis.maven.plugins.unleash.steps.actions.tycho.AbstractTychoVersionsStep.execute(AbstractTychoVersionsStep.java:83)
        at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetReleaseVersionsTycho.execute(SetReleaseVersionsTycho.java:30)
...
```

Full Log & How to reproduce (all projects used are public / FOSS): https://ci.openhab.org/job/sandbox-openhab2-release/979/consoleFull

**Comment by shillner** [comment]
Hi!
Is it possible for you to debug into the tycho steps in order to explore the reason?
I don't see any time frame for me to look into this but I think this can be related to some problem with POM-less tycho builds.
Is project set-up using POM-less tycho?

**Comment by pfink** [comment]
No, we don't use POM-less tycho. I have a NetBeans development environment and can build own versions of unleash with extra log messages. But I don't know how breakpoints can be used during a CLI-triggered build...

**Comment by shillner** [comment]
Ok, I'm not sure but you could start Maven using mvnDebug and attach a remote debugger from your NetBeans to it. [Debugging a Maven Build With mvnDebug](https://dzone.com/articles/debugging-maven-build-mvndebug)
I'll also try to get into it if it's not too much effort.

**Comment by pfink** [comment]
I found the issue now, it's this: https://github.com/openhab/openhab-core/blob/master/pom.xml#L592

As I execute releasebuilds with skipTests=true, `itests` was not part if the reactor and therefore was not found within artifactCoordinates. I'm not sure why unleash looks for it at all though its not part of the reactor.

Anyhow, I think it would be good to treat this case with a proper Exception instead of NPE.
