### ISSUE TITLE
Support for SSH-based SCM connections

### ISSUE THREAD

**Issue by jgangemi** [shillner/unleash-maven-plugin#36]
i'm just trying to perform a basic release against a github repository and i get the following error:

```
[ERROR] Error calling rollback method of Mojo.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback(WorkflowExecutor.java:227)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback(WorkflowExecutor.java:206)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:133)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:114)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:196)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.itemis.maven.plugins.unleash.scm.ScmException: An error occurred while querying the remote git repository for tag '0.2.0'.
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:613)
    at com.itemis.maven.plugins.unleash.steps.actions.TagScm.rollback(TagScm.java:166)
    ... 31 more
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:condevops/hello-world-jenkins.git: USERAUTH fail
    at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:220)
    at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.hasTag(ScmProviderGit.java:607)
    ... 32 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:condevops/hello-world-jenkins.git: USERAUTH fail
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
    at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
    at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:264)
    at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:162)
    at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198)
    ... 34 more
Caused by: com.jcraft.jsch.JSchException: USERAUTH fail
    at com.jcraft.jsch.UserAuthPublicKey.start(UserAuthPublicKey.java:119)
    at com.jcraft.jsch.Session.connect(Session.java:463)
    at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
    ... 38 more
```

is there some configuration setting i am missing?

**Comment by jgangemi** [comment]
also, the `maven-release-plugin` works correctly on this project, i just dropped in the xml from the wiki and updated the version numbers accordingly.

**Comment by shillner** [comment]
Hi, you are using the SSH-based connection to Github which is not yet implemented.
I will schedule this as one of the next points to realize.
Until then you could try the HTTPS-based URL, this one should work.

**Comment by jgangemi** [comment]
do you have a rough eta on when that might be? this plugin will be a no-go for us w/o ssh support.

thanks!!

**Comment by shillner** [comment]
I'm implementing it at the moment and I already have a working implementation here but there is one other thing I'd like to implement before I build a new release. The point is that this will be an API-breaking feature causing a new major release so I try to integrate another feature there which might also break some things.
I think at least at the end of the week the new release will be available.
I will create milestone 2.0.0 for that.

**Comment by shillner** [comment]
A first version is committed on master and will be included in release 2.0.0

**Comment by jgangemi** [comment]
great - i'll check out the source and compile from there.

**Comment by shillner** [comment]
If you build the latest snapshot you will also have to use the latest scm provider for git.
The second point is to set an environment variable `UNLEASH_IT=true` to be able to use the snapshot version of the plugin for release tests.

**Comment by jgangemi** [comment]
after compiling both projects from `master` and setting that env variable, i still get the same error.

**Comment by shillner** [comment]
There is a new parameter for the private key passphrase. It is already listed in the goal documentation. Mittwoch, 17 August 2016, 04:05nachm. +02:00 von Jae Gangemi  notifications@github.com :

**Comment by jgangemi** [comment]
ok - so things work now but storing a passphrase in the pom isn't going to fly either. 

let me see what i can do in terms of putting together a PR that will use an agent. i see the gist you linked to in the code, so it should be pretty straight forward.

p.s. i'm also the same person who filed that jenkins issue about the post build step on the plugin, so unless i get tied down w/ something else, you'll probably be hearing from me a lot in the coming days.

**Comment by shillner** [comment]
I know that this is not the best solution and an agent adapter is planned
for later. It is also not meant in that way that you store the passphrase
in your POM but usually you would pass the passphrase as a system property
or provide it via the Jenkins job configuration. But I know that these
things are not easy to solve but have a higher priority than other issues.
So I think for the next release this (safe scm password passing as well as
PK passphrase using an agent) should be scheduled.

Btw. I was pretty surprised that you are already giving this plugin a
chance even though I haven't already announced it officially ;) Thanks so
far and I hope you can send me some PRs for those issues.

2016-08-17 16:21 GMT+02:00 Jae Gangemi notifications@github.com:

**Comment by jgangemi** [comment]
here's a PR for basic agent support: https://github.com/shillner/unleash-scm-provider-git/pull/2
