### ISSUE TITLE
Rollback of step: SetNextDevVersion fails if SCM commit failed previously

### ISSUE THREAD

**Issue by shillner** [shillner/unleash-maven-plugin#49]
In case that the commit of the development version failed the rollback of step `SetNextDevVersion` fails with an exception like this:

```
[INFO] 23:09:06,517  Preparing project modules for next development cycle.
[INFO] 23:09:12,567  SVN - Committing to remote repository.
[INFO] 23:09:23,271  Rollback of all pom changes necessary for setting of the development version as well as reverting any made SCM commits.
[ERROR] Error calling rollback method of Mojo.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback(WorkflowExecutor.java:227)
        at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback(WorkflowExecutor.java:206)
        at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:133)
        at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:114)
        at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:208)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalStateException: No from revision set (start revision of the reversion)!
        at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
        at com.itemis.maven.plugins.unleash.scm.requests.RevertCommitsRequest$Builder.build(RevertCommitsRequest.java:187)
        at com.itemis.maven.plugins.unleash.steps.actions.SetNextDevVersion.rollback(SetNextDevVersion.java:132)
        ... 31 more
```

**Comment by shillner** [comment]
Fixed in version 2.1.3
