### ISSUE TITLE
SSH authentication fails when passing the private key with the scmSshPrivateKeyEnvVar

### ISSUE THREAD

**Issue by Hofmaier** [shillner/unleash-maven-plugin#80]
unleash:perform-tycho cannot create an SVN tag because SSH authentication fails when passing the private key with with scmSshPrivateKeyEnvVar.
When the Jenkins unleash-plugin is used to release a Eclipse RPC application, SVN authentication fails with the following Error Message.

[ERROR] An exception was caught while processing the workflow step with id 'tagScm'.
com.itemis.maven.plugins.unleash.scm.ScmException: An error occurred during SVN tag creation.
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderSVN.tag(ScmProviderSVN.java:335)
	at com.itemis.maven.plugins.unleash.steps.actions.TagScm.execute(TagScm.java:120)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)
	at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute(AbstractCDIMojo.java:209)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  ...
Caused by: org.tmatesoft.svn.core.SVNAuthenticationException: svn: E170001: Authentication required for '<http://url-to-svn-repository> Project'
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:47)
	at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.authenticationFailed(SVNErrorManager.java:41)
	at org.tmatesoft.svn.core.internal.wc.DefaultSVNAuthenticationManager.getFirstAuthentication(DefaultSVNAuthenticationManager.java:203)
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:716)
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:398)
	at org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:386)
	at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:863)
	at org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doMakeActivity(DAVConnection.java:411)
	at org.tmatesoft.svn.core.internal.io.dav.DAVCommitEditor.createActivity(DAVCommitEditor.java:566)
	at org.tmatesoft.svn.core.internal.io.dav.DAVCommitEditor.openRoot(DAVCommitEditor.java:143)
	at org.tmatesoft.svn.core.internal.wc.SVNCommitUtil.driveCommitEditor(SVNCommitUtil.java:96)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgWcToReposCopy.copy(SvnNgWcToReposCopy.java:244)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgWcToReposCopy.doRun(SvnNgWcToReposCopy.java:118)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgWcToReposCopy.run(SvnNgWcToReposCopy.java:68)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgWcToReposCopy.run(SvnNgWcToReposCopy.java:44)
	at org.tmatesoft.svn.core.internal.wc2.ng.SvnNgOperationRunner.run(SvnNgOperationRunner.java:20)
	at org.tmatesoft.svn.core.internal.wc2.SvnOperationRunner.run(SvnOperationRunner.java:21)
	at org.tmatesoft.svn.core.wc2.SvnOperationFactory.run(SvnOperationFactory.java:1235)
	at org.tmatesoft.svn.core.wc2.SvnOperation.run(SvnOperation.java:294)
	at org.tmatesoft.svn.core.wc2.SvnRemoteCopy.run(SvnRemoteCopy.java:232)
	at org.tmatesoft.svn.core.wc.SVNCopyClient.doCopy(SVNCopyClient.java:600)
	at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderSVN.tag(ScmProviderSVN.java:325)
	... 37 more

The error can be reproduced by executing the follwing command:
mvn unleash:perform-tycho -Dunleash.scmUsername=<SVN_username> -Dunleash.scmSshPrivateKeyEnvVar=<environmentvariable_that_holds_private_key> -Dunleash.releaseVersion=0.23.42 -Dunleash.developmentVersion=0.23.42-SNAPSHOT -X 

The error message contains an http URL. Is this the intented behavior or shouldn't the svn provider use a ssh Uri as defined in den scm tag of the pom.xml?

```
E170001: Authentication required for '<http://url-to-svn-repository> Project 
```

The error occured while using the following configuration:
Apache Maven 3.3.9 (bb52d2502b132ec0a5a3d4c06453c07474323dc5; 2015-11-10T17:41:47+01:00)
Java version: 1.8.0_121, vendor: Oracle Corporation
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.44.2.el7.x86_64", arch: "amd64", family: "unix"

**Comment by Hofmaier** [comment]
The scm tag in the pom is configured as follows:

```
<scm>
	<connection>scm:svn:svn+ssh://username@url-to-svn-repository</connection>
	<developerConnection>scm:svn:svn+ssh://username@url-to-svn-repository</developerConnection>
	<url>svn+ssh://username@url-to-svn-repository/mde</url>
</scm>
```

**Comment by shillner** [comment]
Hi, sorry for the late answer (vacation).
SSH is not yet supported for the SVN connector since there hasn't been the requirement yet.

I don't know when I will be able to have a look into this but feel free to send a PR if you are interested in fixing this!

**Comment by MeyerNils** [comment]
I drafted a first version of SSH support for SVN in https://github.com/shillner/unleash-scm-provider-svn/pull/6 with some open question. 

@Hofmaier, were you trying to trigger unleash locally or from Jenkins?
