### ISSUE TITLE
~/.m2/settings.xml required

### ISSUE THREAD

**Issue by andreasaronsson** [shillner/unleash-maven-plugin#90]
When running `mvn unleash:perform` on a system with only the default settings.xml in `/usr/share/maven/conf`and no settings.xml in ~/.m2 I get the following error:

`[ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: /pathto/userhome/.m2/settings.xml
[ERROR] An exception was caught while processing the workflow step with id 'buildReleaseArtifacts'.
org.apache.maven.plugin.MojoFailureException: Error during project build: 1
	at com.itemis.maven.plugins.unleash.steps.actions.BuildProject.execute(BuildProject.java:81)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep(WorkflowExecutor.java:157)
	at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute(WorkflowExecutor.java:119)`

I was expecting unleash to fallback to using the default settings.xml

**Comment by shillner** [comment]
Ok, checking this one. Thanks for the report!

**Comment by shillner** [comment]
Fixed and included in release 2.7.1 (requires up to 3 hours unitl available on central).

**Comment by andreasaronsson** [comment]
Seems to work just fine.
